name: Update Zipcodes Trigger

on:
  # Allow workflow to only be triggered manually for now
  workflow_dispatch:

jobs:
  run-update-zipcodes-script:
    name: Run Update Zipcodes Workflow
    runs-on: ubuntu-latest

    steps:
      # Check out the repository to the runner
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Python Update Zipcodes script
      - name: Execute Update Zipcodes Script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          PYTHONPATH: ${{ github.workspace }}
        run: python -m etl.update_property_zipcodes
